name: Build and Deploy App

on:
  push:
    branches:
      - development

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print a greeting
        run: echo "Workflow is started!"

      - name: setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependancies
        run: npm Install

      - name: Build the App
        run: npm run build
